import "./globals.css";
// import { TagProvider } from "./context";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* <TagProvider>{children}</TagProvider> */}
        {children}
      </body>
    </html>
  );
}
